## SVM

SVM用の関数を定義

In [1]:
#必要なライブラリを import 
from sklearn import datasets
import numpy as np
import sklearn
from sklearn import datasets
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [2]:
# クラスラベルを振り直す用の関数
def fix_data(y,one_class):
    y_fix = []
    for i in y:
        if i == one_class:
            y_fix.append(1)
        else:
            y_fix.append(-1)
        
    return y_fix

In [3]:
# SVMを作成する関数：係数ベクトルとバイアス項を返す
def get_svm_params(X,y):
    # データの標準化処理
    sc = StandardScaler()
    sc.fit(X)
    X_std = sc.transform(X)

    # 線形SVMのインスタンスを生成
    model = SVC(kernel='linear', random_state=None)
    # モデルの学習。fit関数で行う。
    model.fit(X_std, y)

    W = model.coef_
    b = model.intercept_

    return W,b

# Neaural Networt

In [4]:
import matplotlib.pyplot as plt
plt.style.use('ggplot')

In [5]:
import matplotlib.pyplot as plt
plt.style.use('ggplot')

## 重みの初期値をSVMで求める

In [6]:
from sklearn import datasets
iris = datasets.load_iris()
features = iris.data
targets = iris.target

In [7]:
X = iris.data

In [8]:
#クラスラベルを取得
y = iris.target

In [9]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
y_０ = fix_data(y,0)
y_０ = np.array(y_０)
y_0

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [11]:
y_1 = fix_data(y,1)
y_1 = np.array(y_1)
y_1

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [12]:
y_2 = fix_data(y,2)
y_2 = np.array(y_2)
y_2

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [13]:
W0,b0 = get_svm_params(X, y_0)

In [14]:
W1,b1 = get_svm_params(X, y_1)

In [15]:
W2,b2 = get_svm_params(X, y_2)

## 重みをnpの配列に整形

In [16]:
W0

array([[-0.4395772 ,  0.33225827, -0.89103945, -0.92356114]])

In [17]:
b1.tolist()

[-0.7811106915502619]

In [18]:
b = np.array([b0[0],b1[0],b2[0]])

In [19]:
b

array([-1.47415783, -0.78111069, -3.09773099])

In [20]:
W0[0]

array([-0.4395772 ,  0.33225827, -0.89103945, -0.92356114])

In [21]:
b.T

array([-1.47415783, -0.78111069, -3.09773099])

In [22]:
W = np.array((W0[0],W1[0],W2[0]))

In [23]:
W.T

array([[-0.4395772 ,  0.18130363, -0.31017791],
       [ 0.33225827, -1.08743388, -0.60142345],
       [-0.89103945,  0.71789162,  2.45750269],
       [-0.92356114, -1.03946953,  2.44474903]])

In [24]:
W.T[1]

array([ 0.33225827, -1.08743388, -0.60142345])

In [25]:
W_ = W.T

In [26]:
W_ 

array([[-0.4395772 ,  0.18130363, -0.31017791],
       [ 0.33225827, -1.08743388, -0.60142345],
       [-0.89103945,  0.71789162,  2.45750269],
       [-0.92356114, -1.03946953,  2.44474903]])

In [27]:
init_1 = np.array([W_,b])

In [28]:
# この形に配列を整形する
my_init_1 =[
    [
        [-0.7884204 , -0.6338457 , -0.25281274],
        [ 0.5329331 , -0.19831198, -0.12317081],
        [-0.83381253, -0.07458979,  0.955629  ],
        [-0.02403361,  0.02735829,  0.7528269 ]],
 [ 0.111        ,  0.21        , -0.16679405],
]

## SVMで求めた重みを用いてNNを作成

In [29]:
#kerasに必要なものをインポート
from keras.models import Sequential
from keras.layers import Dense, Activation

Using TensorFlow backend.


In [30]:
#モデルの設定
model = Sequential()
model.add(Dense(3, input_dim=4))
model.add(Activation('softmax')) 
# 重みをセットする
# TODO：
# ここでSVMで求めた重みを整形してsetしたい
model.set_weights(my_init_1)
# TODO：
# 中間層の値を出力させ，それをSVMの入力として重みを求める
model.compile(optimizer='SGD',loss='sparse_categorical_crossentropy',metrics=['accuracy'])
model.fit(features, targets, nb_epoch=20, batch_size=5)

W0813 15:47:15.317127 4657550784 deprecation_wrapper.py:119] From /anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0813 15:47:15.398117 4657550784 deprecation_wrapper.py:119] From /anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0813 15:47:15.401639 4657550784 deprecation_wrapper.py:119] From /anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0813 15:47:15.462388 4657550784 deprecation_wrapper.py:119] From /anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:174: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

W0813 15:47:15.464344 4657550784 deprecation_wrapper

Epoch 1/20
150/150 [==============================] - 0s 1ms/step - loss: 1.2456 - acc: 0.5667
Epoch 2/20
150/150 [==============================] - 0s 274us/step - loss: 0.4917 - acc: 0.8467
Epoch 3/20
150/150 [==============================] - 0s 174us/step - loss: 0.4681 - acc: 0.8867
Epoch 4/20
150/150 [==============================] - 0s 348us/step - loss: 0.4588 - acc: 0.8800
Epoch 5/20
150/150 [==============================] - 0s 321us/step - loss: 0.4459 - acc: 0.8600
Epoch 6/20
150/150 [==============================] - 0s 352us/step - loss: 0.4464 - acc: 0.8933
Epoch 7/20
150/150 [==============================] - 0s 252us/step - loss: 0.4256 - acc: 0.8533
Epoch 8/20
150/150 [==============================] - 0s 254us/step - loss: 0.4289 - acc: 0.9067
Epoch 9/20
150/150 [==============================] - 0s 222us/step - loss: 0.4143 - acc: 0.8867
Epoch 10/20
150/150 [==============================] - 0s 227us/step - loss: 0.4129 - acc: 0.8867
Epoch 11/20
150/150 [==========