In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('ggplot')

In [2]:
from sklearn import datasets
iris = datasets.load_iris()
features = iris.data
targets = iris.target

In [21]:
#kerasに必要なものをインポート
from keras.models import Sequential
from keras.layers import Dense, Activation
import numpy as np

In [22]:
#モデルの設定
model = Sequential()
model.add(Dense(3, input_dim=4))
model.add(Activation('relu'))
model.compile(optimizer='SGD',loss='sparse_categorical_crossentropy',metrics=['accuracy'])
model.fit(features, targets, nb_epoch=20, batch_size=5)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  


Epoch 1/20
150/150 [==============================] - 0s 1ms/step - loss: 0.9616 - acc: 0.5733
Epoch 2/20
150/150 [==============================] - 0s 216us/step - loss: 0.8842 - acc: 0.6267
Epoch 3/20
150/150 [==============================] - 0s 274us/step - loss: 0.8528 - acc: 0.6333
Epoch 4/20
150/150 [==============================] - 0s 200us/step - loss: 0.8280 - acc: 0.6533
Epoch 5/20
150/150 [==============================] - 0s 223us/step - loss: 0.8023 - acc: 0.6600
Epoch 6/20
150/150 [==============================] - 0s 224us/step - loss: 0.7843 - acc: 0.6600
Epoch 7/20
150/150 [==============================] - 0s 245us/step - loss: 0.7632 - acc: 0.6600
Epoch 8/20
150/150 [==============================] - 0s 227us/step - loss: 0.7418 - acc: 0.6533
Epoch 9/20
150/150 [==============================] - 0s 226us/step - loss: 0.7227 - acc: 0.6933
Epoch 10/20
150/150 [==============================] - 0s 221us/step - loss: 0.7074 - acc: 0.6933
Epoch 11/20
150/150 [==========

In [23]:
model.get_weights()

[array([[-0.5599638 , -0.39195663, -0.6654287 ],
        [ 0.30723965, -0.34116715,  0.39544922],
        [-0.4735231 , -0.59187007,  1.0976638 ],
        [ 0.28427064,  0.38473403,  0.3770886 ]], dtype=float32),
 array([ 0.        ,  0.        , -0.04615001], dtype=float32),
 array([[ 0.08016467,  0.29940224, -0.23773599],
        [-0.33884907, -0.9336932 ,  0.9046979 ],
        [-0.9472477 ,  0.5577616 ,  0.97606945]], dtype=float32),
 array([ 0.80642265, -0.01709472, -0.78932756], dtype=float32)]