## SVM

SVM用の関数を定義

In [111]:
#必要なライブラリを import 
from sklearn import datasets
import numpy as np
import sklearn
from sklearn import datasets
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [112]:
# クラスラベルを振り直す用の関数
def fix_data(y,one_class):
    y_fix = []
    for i in y:
        if i == one_class:
            y_fix.append(1)
        else:
            y_fix.append(-1)
        
    return y_fix

In [113]:
# SVMを作成する関数：係数ベクトルとバイアス項を返す
def get_svm_params(X,y):
    # データの標準化処理
    sc = StandardScaler()
    sc.fit(X)
    X_std = sc.transform(X)

    # 線形SVMのインスタンスを生成
    model = SVC(kernel='linear', random_state=None)
    # モデルの学習。fit関数で行う。
    model.fit(X_std, y)

    W = model.coef_
    b = model.intercept_

    return W,b

# Neaural Networt

In [114]:
import matplotlib.pyplot as plt
plt.style.use('ggplot')

In [115]:
import matplotlib.pyplot as plt
plt.style.use('ggplot')

## 重みの初期値をSVMで求める

In [116]:
from sklearn import datasets
iris = datasets.load_iris()
features = iris.data
targets = iris.target

In [117]:
X = iris.data

In [118]:
#クラスラベルを取得
y = iris.target

In [119]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [120]:
y_０ = fix_data(y,0)
y_０ = np.array(y_０)
y_0

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [27]:
y_1 = fix_data(y,1)
y_1 = np.array(y_1)
y_1

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [28]:
y_2 = fix_data(y,2)
y_2 = np.array(y_2)
y_2

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [17]:
W0,b0 = get_svm_params(X, y_0)

In [29]:
W1,b1 = get_svm_params(X, y_1)

In [39]:
W2,b2 = get_svm_params(X, y_2)

## 重みをnpの配列に整形

In [43]:
W0

array([[-0.4395772 ,  0.33225827, -0.89103945, -0.92356114]])

In [42]:
b1.tolist()

[-0.7811106915502619]

In [59]:
b = np.array([b0[0],b1[0],b2[0]])

In [60]:
b

array([-1.47415783, -0.78111069, -3.09773099])

In [61]:
W0[0]

[-0.43957720145668827,
 0.332258272454104,
 -0.8910394480605555,
 -0.9235611418168851]

In [131]:
b.T

array([-1.47415783, -0.78111069, -3.09773099])

In [132]:
W = np.array((W0[0],W1[0],W2[0]))

In [133]:
W.T

array([[-0.4395772 ,  0.18130363, -0.31017791],
       [ 0.33225827, -1.08743388, -0.60142345],
       [-0.89103945,  0.71789162,  2.45750269],
       [-0.92356114, -1.03946953,  2.44474903]])

In [134]:
W.T[1]

array([ 0.33225827, -1.08743388, -0.60142345])

In [135]:
W_ = W.T

In [136]:
W_ 

array([[-0.4395772 ,  0.18130363, -0.31017791],
       [ 0.33225827, -1.08743388, -0.60142345],
       [-0.89103945,  0.71789162,  2.45750269],
       [-0.92356114, -1.03946953,  2.44474903]])

In [129]:
init_1 = np.array([W_,b])

In [130]:
init_1

array([list([[-0.43957720145668827, 0.18130362773562525, -0.31017791474341183], [0.332258272454104, -1.0874338846253866, -0.6014234520600548], [-0.8910394480605555, 0.7178916166904605, 2.4575026852847293], [-0.9235611418168851, -1.0394695334257165, 2.444749026199184]]),
       array([-1.47415783, -0.78111069, -3.09773099])], dtype=object)

## SVMで求めた重みを用いてNNを作成

In [105]:
#kerasに必要なものをインポート
from keras.models import Sequential
from keras.layers import Dense, Activation

In [110]:
#モデルの設定
model = Sequential()
model.add(Dense(3, input_dim=4, init=my_init))
model.add(Activation('softmax')) 
model.set_weights(init_1)
model.compile(optimizer='SGD',loss='sparse_categorical_crossentropy',metrics=['accuracy'])
model.fit(features, targets, nb_epoch=20, batch_size=5)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(3, input_dim=4, kernel_initializer=[[[0.43377...)`
  This is separate from the ipykernel package so we can avoid doing imports until


ValueError: Could not interpret initializer identifier: [[[0.43377656, 0.5432864, -0.20303631], [0.13959564, -1.0050316, -0.90519124], [-0.69614434, 0.36312348, 0.9486076], [-0.39720488, 0.01902995, 0.6168851]], [0.10754874, -0.02252603, -0.08502266]]